### ISSUE TITLE
Add arg to not release client in slate-client-release.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#101]
Add something like the following to `.github/workflows/slate-client-release.yml`:
```yaml
on:
  workflow_call:
    inputs:
      ...
      deploy_client:
        description: Whether to deploy the client to GitHub
        required: false
        default: true
        type: boolean
      ...
```
