### ISSUE TITLE
Add Slack notifications

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#52]
A previous way of notifying Slack is shown below:
```yaml
- name: Notify Slack of Failure
  if: failure()
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
  uses: voxmedia/github-action-slack-notify-build@v1
  with:
    channel: github-actions
    status: FAILED
    color: danger
```
