### ISSUE TITLE
Add helm_working_directory to helm-upgrade and chart-diff-lint

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#59]
A use-case has come up where we need to change the default working directory where Helm command are executed. Please add a `helm_working_directory` input to `helm-upgrade.yml` and `chart-diff-lint.yml`. E.g.
```yaml
helm_working_directory:
  description: The relative directory where Helm commands will execute.
  required: false
  default: "."
  type: string
```
