### ISSUE TITLE
Implement docker/login-action

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#63]
Switch to using the `docker/login-action`. For example, instead of:
```yaml
- name: Log in to CR
  run: echo '${{ secrets.cr_password }}' | docker login https://${{ inputs.cr_domain }} -u '${{ secrets.cr_username }}' --password-stdin

```
use:
```yaml
- name: Authenticate with OSG Harbor
  uses: docker/login-action@v2
  with:
    registry: "${{ inputs.cr_domain }}"
    username: "${{ secrets.cr_username }}"
    password: "${{ secrets.cr_password }}"
```
