### ISSUE TITLE
Add slack-notify-failure composit action

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#65]
Define a Slack notification composite action here. This will allow us to pivot to different marketplace actions if necessary without having to hunt down references in our many Git repositories.

Use the following as an example (from [4dd6def](https://github.com/slateci/docker-images/blob/4dd6def97e92c34f3cf8de9c8babc850df388fa9/.github/workflows/push.yml)):
```yaml
- name: Notify Slack of Failure
  if: failure()
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
  uses: voxmedia/github-action-slack-notify-build@v1
  with:
    channel: github-actions
    status: FAILED
    color: danger
```
