### ISSUE TITLE
Add missing gitconfig to image-build-push.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#69]
Add the following to `.github/workflows/image-build-push.yml`:
```yaml
- name: Configure Git
  run: |
    git config --global user.name "${{ github.actor }}"
    git config --global user.email "${{ github.actor }}@users.noreply.github.com"
```
