### ISSUE TITLE
VERSION_OVERRIDE incorrect in slate-client-release.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/github-actions#88]
The override value below:
```yaml
 - name: Run make
  working-directory: ./checkout/build
  run: |-
    export VERSION_OVERRIDE=$(echo ${{ github.ref }} | cut -d'v' -f 2)
    make
```
should be instead determined as follows:
```yaml
- name: Run make
  working-directory: ./checkout/build
  run: |-
    export VERSION_OVERRIDE=${{ env.RELEASE_VERSION }}
    make
```
